# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 一根札记
email: your-email@domain.com
author: Hayden Wei
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.haydenwei.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  gnodiah
date_format: "%B %e, %Y at %H:%M %Z"
category_title_prefix: ""
permalink: /:year/:month/:title

# Build settings
markdown: rdiscount
blog_index_sidebar: the_pug_automatic.html
page_sidebar: the_pug_automatic.html
post_sidebar: the_pug_automatic.html
pygments: false
paginate: 10
pagination_dir: blog
